### ISSUE TITLE
Why this lib does not based on googleapis_auth?

### ISSUE THREAD

**Issue by guyluz11** [Skycoder42/firebase_auth_rest#2]
I was wondering.
If you are saying in the package that 

> Uses the official REST-API endpoints

Wouldn't it be less work to based this on the official package from google [googleapis_auth](https://pub.dev/packages/googleapis_auth/install) ?.
It support all platforms and will `"Provides support for obtaining OAuth2 credentials to access Google APIs."` for you.

**Comment by Skycoder42** [comment]
This package is for Firebase, not Google. You can combine the two, using googleapis_auth to sign into your Google account and then use these credentials with this library to sign into your firebase project. These two are relate, but two very different things.

**Comment by Skycoder42** [comment]
You could use sign in with Facebook, apple, your email or anonymous into firebase. This package does not handle the initial credentials

**Comment by guyluz11** [comment]
Thanks, I think I understand it now better.
