### ISSUE TITLE
Update token timout return with null check exception.

### ISSUE THREAD

**Issue by guyluz11** [Skycoder42/firebase_auth_rest#3]
I am currently replacing [`firedart`](https://pub.dev/packages/firedart) auth part with this package ([you can see my fork here](https://github.com/guyluz11/firedart?organization=guyluz11&organization=guyluz11)).
Writing to cloud firestore works and I can even listen to changes (real-time stream).

After couple of hours of listening to changes (real-time stream) it is crashing from this package

![Error](https://user-images.githubusercontent.com/9304740/121809388-423d2a00-cc65-11eb-8825-c4db57532fb2.png)

Calling with `autoRefresh = true`

**Comment by guyluz11** [comment]
Now that the bug in HTTP has been solved this issue **isn't** fixed yet.

This issue occurs when trying to do HTTP send request after client has been closed, so we need to maybe stop the call or recreate the user or throw exception whenever that happen.

**Comment by Skycoder42** [comment]
So, if I understand you correctly, your situation is as follows:
1. You create a FirebaseAuth instance with a dedicated client
2. You use that API to create a User, who auto-refreshes their credentials automatically
3. After some time, you close the originally used client
4. The next time the credentials are to be refreshed, it crashes.

Is that correct? If yes, why do you dispose the client. What would you expect to happen in this case?

**Comment by guyluz11** [comment]
I am not closing any client.
Only listening to real-time stream.

**Comment by Skycoder42** [comment]
Then why is the client closed? The code where the exception occurs does nothing special, it simply sends a HTTP-Post request via the http packages Client to renew the idToken of the logged in account. So somewhere, that client must be closed... 

You could try to set `FirebaseAccount.autoRefresh` to false and call `FirebaseAccount.refresh()` manually, this way you can react to the exception and recreate the account. Also, this might help in figuring out where the connection fails. For example, you could try to call refresh 5 minutes after the streaming has started, just to see if it happens then to.

**Comment by Skycoder42** [comment]
Are you still having the problem?

**Comment by guyluz11** [comment]
The pull request is still in process

**Comment by Skycoder42** [comment]
Whatever the problem is, I cannot reproduce it. I ran a small script, running for hours without problems, over multiple session renews. The code and the logs are added below:

----------
Code: 

´´´.dart
Future<void> main(List<String> arguments) async {
  final client = Client();
  final auth = FirebaseAuth(
    client,
    arguments[0],
  );

  final account = await auth.signInWithPassword(
    arguments[1],
    arguments[2],
  );
  final idTokenSub = account.idTokenStream.listen(
    (event) => print('idToken: $event'),
    onDone: () => print('idToken: DONE'),
    onError: (Object e, StackTrace? s) => print('idToken: $e\n$s'),
    cancelOnError: false,
  );

  final database = FirebaseDatabase(
    account: account,
    database: 'dart-firebase-rest',
    client: client,
    basePath: '/firebase_sync/${account.localId}/',
  );

  final store = database.rootStore.subStore<dynamic>(
    path: 'renew',
    onDataFromJson: (dynamic json) => json,
    onDataToJson: (dynamic data) => data,
    onPatchData: (dynamic data, Map<String, dynamic> changes) =>
        throw UnimplementedError(),
  );

  final stream = AutoRenewStream(store.streamAll);
  final sub = stream.listen(
    print,
    onDone: () => print('data: DONE'),
    onError: (Object e, StackTrace? s) => print('data: $e\n$s'),
    cancelOnError: false,
  );

  try {
    await store.destroy();
    // ignore: literal_only_boolean_expressions
    while (true) {
      await Future<void>.delayed(const Duration(minutes: 5));
      await store.create(DateTime.now().toIso8601String());
    }
  } catch (e, s) {
    print('$e\n$s');
  } finally {
    await sub.cancel();
    await database.dispose();
    await idTokenSub.cancel();
    account.dispose();
    client.close();
  }
}
´´´

----------
Logs:
[logs.txt](https://github.com/Skycoder42/firebase_auth_rest/files/6937857/logs.txt)

**Comment by guyluz11** [comment]
Ok so lets close it for now and I will reopen it in case it comes back.

Thanks
