### ISSUE TITLE
"null-safety" branch can be removed

### ISSUE THREAD

**Issue by guyluz11** [Skycoder42/firebase_auth_rest#4]
"null-safety" branch can be removed as `master` branch is already null safety.

And all commits have merged 
![image](https://user-images.githubusercontent.com/9304740/122221417-eddeb800-ceb9-11eb-8cdc-2085445c216e.png)

**Comment by Skycoder42** [comment]
Sure, It could, but what is the point - there is no damage in keeping the branch
