### ISSUE TITLE
when i logIn and then close app and try to open it again , i logIn again .

### ISSUE THREAD

**Issue by Joseph-Nathan** [Skycoder42/firebase_auth_rest#6]
can you provide current FireBaseAccount || User , or any idea to handle that .
thanks for you package.

**Comment by Skycoder42** [comment]
You can use [`FirebaseAccount.restore`](https://pub.dev/documentation/firebase_auth_rest/latest/firebase_auth_rest/FirebaseAccount/restore.html) for that
