### ISSUE TITLE
Exception is thrown when statusCode is >=300 but it is not handled

### ISSUE THREAD

**Issue by nayeemtby** [Skycoder42/firebase_auth_rest#7]
There are important messages in the body but they are not passed down and instead an exception is thrown.

![image](https://user-images.githubusercontent.com/71181265/147463202-0decd26b-8917-4b48-8e0f-9d0122cb3a34.png)

**Comment by nayeemtby** [comment]
My bad. I did do a try catch in an inner function which calls the FirebaseAuth signInWithEmailAndPassword but that didn't catch the exception, but the outer function caught it. Weird 🤔

**Comment by Skycoder42** [comment]
That is indeed strange. Probably async await issues?

**Comment by nayeemtby** [comment]
I put await in both of the callers, don't know what went wrong. If no one else is facing the problem then it's not a problem 🥴
